[package]
name = "tonic-ws-transport"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[features]
default = ["native"]
native = ["tokio/net", "tokio/io-util", "tokio/stream", "tonic", "tokio-tungstenite"]

[dependencies]
http = "0.2.1"
bytes = "0.5.6"
thiserror = "1.0.22"
tower = "0.3.1"
tower-service = "0.3.0"
pin-project = "1.0.1"
tokio = { version = "0.2.2" }
futures-util = "0.3.7"
futures = "0.3.7"
cfg-if = "1.0.0"
tungstenite = { version = "0.11.0", default-features = false }

tonic = {version = "0.3.1", optional = true }
tokio-tungstenite = {version = "0.11.0", optional = true }

[build-dependencies]
tonic-build = "0.3.1"

[dev-dependencies]
tokio = { version = "0.2.2", features = ["macros"] }
prost = "0.6.1"
