[workspace]
members = [
    "transport",
    "examples/wasm-client",
    "examples/helloworld",
]

[patch.crates-io]
tonic = { git = "https://github.com/boxdot/tonic", branch = "tonic-ws-transport" }
h2 = { git = "https://github.com/boxdot/h2", branch = "tonic-ws-transport" }
tower-buffer = { git = "https://github.com/boxdot/tower", branch = "tonic-ws-transport" }
