[package]
name = "wasm-client"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"
publish = false

[dependencies]
tonic-ws-transport = { path = "../../transport", default-features = false }
# tonic = { version = "0.3.1", default-features = false, features = ["client", "codegen", "prost"] }
tonic = { path = "../../../tonic/tonic", default-features = false, features = ["client", "codegen", "prost"] }
prost = "0.6.1"

[build-dependencies]
# Note: no "transport" feature => generated client does not have transport dependent code
tonic-build = { version = "0.3.1", default-features = false, features = ["prost", "rustfmt"] }

# [patch.crates-io]
